### ISSUE TITLE
更新计划

### ISSUE THREAD

**Issue by hsiaosiyuan0** [chenshy39/regular-autocomplete#3]
在当前，依然更新插件首先给人的感觉就是“不合时宜”。不过既然现在“将所有页面都迁移”的任务也被认为几乎不可执行的，那么继续完善开发体验势必会提高参与到其中的同学工作效率。我觉得随着时间的推移，这部分的工作意义可能会慢慢体现出来（我目前因此插件而深有体会😀），虽然它不能惠及大部分同学，但是它的意义会比现在看起来的要大。

我想将更新内容归纳为下面几项：

* 将 VSCode Marketplace 中插件进行统一，现在包括我提交的一共有三个，希望可以统一成一个。不过不知道能不能行，我感觉是不是因为之前的认证丢了才发了两份😀。统一的目的是希望有需求的同学可以尽快的找到插件本身

* 将插件支持的书写形式固定为 .rgl 文件和 JS 文件内联的两种，这样减少后续可能的工作内容，比如格式化的工作，将只支持这两种书写形式，也稍微规范一下书写形式，现在形式略多：
  
  * .vue 的借助 vue 相关插件来高亮的 orz
  * .tpl 的，里面单独写模板的形式
  * .rgl 
  * JS 文件内联的

  我们将只支持 .rgl 和 JS 内联的两种形式，基于以下几点：

  * .rgl 和 JS 内联分别对应当前的 vue 和 jsx 的形式，实践较多，接受度也较高
  * .tpl 单独写的，数量应该不多，迁移到 .rgl 的成本应该也不大（待定，因为社交里面没有这种情况）
  * .vue 的直接将后缀修改为 .rgl 即可

* 模板格式化的功能以大致完成，待集成到插件中。不过可能需要将格式化继承为 eslint 中，这样对 JS 文件还是 .rgl 文件进行统一的格式化。

**Comment by ChenShuy1** [comment]
@hsiaosiyuan0 
1. 关于整合问题。之前有一个regular-autocomplete是因为一开始就是想要一个简单的补全插件，后面发现插件可以承载更多工作于是干脆换一个插件再发一次。如果可以的话，当然能整合是最好的啦。
2. 插件可以支持字符串模板和.rgl文件的写法高亮，但是感觉统一的话还是挺难执行的，需要看插件的推广范围。
3. 期待格式化：）

**Comment by hsiaosiyuan0** [comment]
**关于整合**

- https://marketplace.visualstudio.com/items?itemName=chenshuyi.regular
- https://marketplace.visualstudio.com/items?itemName=chenshuyi.regular-autocomplete
- https://marketplace.visualstudio.com/items?itemName=hsiaosiyuan.regularjs

目前是上面这三个。我了解到 VSCode 插件是不支持重命名的，所以：

1. 将 `chenshuyi.regular-autocomplete` 和我的 `hsiaosiyuan.regularjs` 删掉，后续功能都维护到 `chenshuyi.regular` 中，因为它的命名挺明确的。我发现 `chenshuyi.regular-autocomplete` 和 `chenshuyi.regular` 都指向的同一个 git repo？所以如果用这个方式的话，我的代码还是往这边来提交吗？

2. 我们把这三个都从 VSCode Marketplace 中删掉，重新创建一个新的，之后统一把功能维护到这个新的中

**关于推广**

维护的插件的目的是希望方便组内的开发，不过我们不会强迫大家来将现有的代码进行统一、或者说限制大家新代码的编写方式。大家还是可以自由的选择自己喜欢的形式来写，不过我们将只支持这两种相对规范的形式，并让使用该形式的同学因为我们的插件而获得比较好的编码体验，我觉得这样应该就差不多了

**关于格式化**

其实基本上已经差不多完成了，[演示](https://www.youtube.com/watch?v=0nixyvc2asg&feature=youtu.be)。剩下都是 corner cases，以及整合到 .rgl 文件的格式化。所以比较依赖上面的第一步工作，因为我这边平时用的时候都会有比较相对高频的 bugfix，所以希望就固定到一个确定的仓库和插件，这样就固定维护和安装同一个插件了。确实日常工作会比较繁琐一些，所以麻烦抽时间我们一起把第一步整合的工作给落地一下😀

**Comment by ChenShuy1** [comment]
指向同一个repo会有什么问题吗？代码提交不都是往repo上提？

**Comment by hsiaosiyuan0** [comment]
我以为 regular-autocomplete 和 regular-tool 可能是两个不同的 repos，可能是链接填错了 - -
